name: C/C++ CI

on: [push]

jobs:
  test:
    name: Build test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: make strict
      shell: sh
      working-directory: ./